version: "3.5"

services:
    laravel-app:
        build:
            context: "."
            args:
                uid: ${UID}
        container_name: laravel-app
        ports:
            - 8000:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        command: sh -c "composer install && php artisan key:generate && php artisan jwt:secret && php artisan migrate"
        networks:
            backend:
                aliases:
                    - app

    mysql-db:
        image: mysql:5.7
        container_name: mysql-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=securerootpassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            backend:
                aliases:
                    - mysql-db

networks:
    backend:
        name: backend-network
